### ISSUE TITLE
hubstorage.batchuploader.ValueTooLarge: value exceeds max encoded size of 1048576 bytes

### ISSUE THREAD

**Issue by umrashrf** [scrapinghub/python-hubstorage#23]
Here https://staging.scrapinghub.com/p/1572/job/20/3/#log/line/485613

It seems items larger than 1MB in size won't be stored in Hubtstorage. Given the fact that hubstorage can store any size of item, shouldn't it store the item and generate a warning rather than raising an error?

**Comment by umrashrf** [comment]
For reference https://github.com/scrapinghub/hubstorage/issues/223

**Comment by dangra** [comment]
Hubstorage won't store the item anyway, the check is *also* in python-hubstorage because otherwise Hubstorage will return error 413 and refuse to store the whole batch of items. If you intend to change this behavior please report the issue to Hubstorage issue tracker and discuss there.

**Comment by umrashrf** [comment]
ok thanks @dangra, let me see if that only item can be ignored otherwise I will reopen hubstorage issue.
