### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by codinguncut** [scrapinghub/python-hubstorage#69]
when I try to use "hubstorage" with python 3.5 I get the error message.

"ImportError: No module named 'Queue'"

apparently this particular error can be fixed with the below, but there may be more changes required to support python 3.

```
if is_py2:
    import Queue as queue
else:
    import queue as queue
```

**Comment by immerrr** [comment]
Python 3 support is merged into master, but not released yet, stay tuned.

**Comment by chekunkov** [comment]
Just released a [new version](https://pypi.python.org/pypi/hubstorage/0.23.0), please try it
